### ISSUE TITLE
Mathematical and logical operations not supported

### ISSUE THREAD

**Issue by Rintarou** [Callidon/sage-client#4]
When running queries that contain mathematical operations (=,+,-,*,...); most notably the queries from the
[project-expression/](https://www.w3.org/2009/sparql/docs/tests/summary.html#project-expression-projexp01) folder,
of the [w3c SPARQL 1.1 compliance benchmark](https://www.w3.org/2009/sparql/implementations/)

we obtain empty invalid results:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<sparql xlmns="http://www.w3.org/2005/sparql-results#">
  <head>
    <variable name="x"/>
    <variable name="y"/>
    <variable name="z"/>
    <variable name="eq"/>
  </head>
  <results>
    <result>
      <binding name="x">
        <uri/>
      </binding>
      <binding name="y">
        <uri/>
      </binding>
      <binding name="z">
        <uri/>
      </binding>
      <binding name="eq">
        <uri/>
      </binding>
    </result>
</results>
</sparql>
```

There is no current support for queries of the following form:
```sparql
projeprefix ex:	<http://www.example.org/schema#>
prefix in:	<http://www.example.org/instance#>

select ?x ?y ?z ((?y = ?z) as ?eq) where {
  ?x ex:p ?y .
  ?x ex:q ?z
}
```

altough this issue affects project-expression most evidently, but this kind of mathematical operator is used widely across the w3c benchmark, so it is rather relevant.

**Comment by Slaanaroth** [comment]
Math operations are handled, tests including math ops that still fail are the result of other unhandled operations
